function validation = n_system_validation(meanFieldResults,options)

if nargin < 1 || ~isstruct(meanFieldResults)
    error('Supply the struct returned by run_simulation.');
end

if nargin < 2 || isempty(options)
    options = struct();
elseif isnumeric(options) && isscalar(options)
    options = struct('numParticles',options);
elseif ~isstruct(options)
    error('The second input must be a scalar or struct.');
end

cfg = meanFieldResults.cfg;
Y = reshape(meanFieldResults.leader,1,[]);
Rho = meanFieldResults.density;

boundaryCondition = validatestring( ...
    lower(char(cfg.domain.boundary)), ...
    {'periodic','zero_flux','open'});

options = complete_options(options,cfg);

N = options.numParticles;
M = cfg.numTimeSteps;
dt = cfg.dt;

comparisonIndices = unique([ ...
    1:options.comparisonEvery:(M+1), ...
    M+1]);

comparisonTimes = ...
    cfg.time(comparisonIndices);

numComparisons = ...
    numel(comparisonIndices);

comparisonSlot = zeros(M+1,1);
comparisonSlot(comparisonIndices) = ...
    1:numComparisons;

comparisonEdges = linspace( ...
    cfg.domain.lower, ...
    cfg.domain.upper, ...
    options.numComparisonCells+1).';

comparisonCentres = 0.5.*( ...
    comparisonEdges(1:end-1) ...
    +comparisonEdges(2:end));

comparisonDx = ...
    comparisonEdges(2)-comparisonEdges(1);

meanFieldComparison = zeros( ...
    options.numComparisonCells, ...
    numComparisons);

for index = 1:numComparisons
    meanFieldComparison(:,index) = ...
        restrict_density( ...
            Rho(:,comparisonIndices(index)), ...
            comparisonEdges,cfg);
end

numOverlayParticles = min( ...
    N,options.maxOverlayParticles);

overlayParticleIndices = unique(round( ...
    linspace(1,N,numOverlayParticles))).';

particleTrajectories = nan( ...
    numel(overlayParticleIndices),M+1);

empiricalDensitySum = zeros( ...
    options.numComparisonCells, ...
    numComparisons);

l1Error = zeros( ...
    numComparisons,options.numRealizations);

l2Error = zeros( ...
    numComparisons,options.numRealizations);

w1Error = zeros( ...
    numComparisons,options.numRealizations);

massError = zeros( ...
    numComparisons,options.numRealizations);

finalParticles = nan( ...
    N,options.numRealizations);

for realization = 1:options.numRealizations

    rng( ...
        options.randomSeed+realization-1, ...
        'twister');

    X = sample_initial_particles( ...
        Rho(:,1),cfg,N, ...
        options.initialSampling);

    alive = true(N,1);

    if realization == 1
        particleTrajectories(:,1) = ...
            X(overlayParticleIndices);
    end

    [empiricalDensity,metrics] = ...
        compare_state( ...
            X,N, ...
            meanFieldComparison(:,1), ...
            comparisonEdges, ...
            comparisonDx, ...
            boundaryCondition);

    empiricalDensitySum(:,1) = ...
        empiricalDensitySum(:,1) ...
        +empiricalDensity;

    l1Error(1,realization) = metrics.l1;
    l2Error(1,realization) = metrics.l2;
    w1Error(1,realization) = metrics.w1;
    massError(1,realization) = metrics.mass;

    for k = 1:M

        activeIndex = find(alive);

        if ~isempty(activeIndex)

            activeX = X(activeIndex);

            followerVelocity = ...
                particle_interaction_velocity( ...
                    activeX,cfg, ...
                    options.interactionBlockSize,N, ...
                    boundaryCondition);

            displacementToLeader = ...
                activeX-Y(k);

            if strcmp(boundaryCondition,'periodic')
                displacementToLeader = ...
                    periodic_displacement( ...
                        displacementToLeader, ...
                        cfg.domain);
            end

            leaderWeight = cfg.leaderKernel( ...
                abs(displacementToLeader), ...
                cfg.leaderKernelParameters);

            leaderVelocity = ...
                -cfg.leaderFieldScale ...
                .*leaderWeight ...
                .*displacementToLeader;

            activeX = activeX ...
                +dt.*( ...
                    followerVelocity ...
                    +leaderVelocity) ...
                +cfg.sigmaX.*sqrt(dt) ...
                    .*randn(numel(activeIndex),1);

            switch boundaryCondition

                case 'periodic'
                    activeX = ...
                        wrap_periodic( ...
                            activeX,cfg.domain);

                case 'zero_flux'
                    activeX = ...
                        reflect_state( ...
                            activeX,cfg.domain);

                case 'open'
                    outside = ...
                        activeX < cfg.domain.lower ...
                        |activeX > cfg.domain.upper;

                    removedIndex = ...
                        activeIndex(outside);

                    alive(removedIndex) = false;
                    activeX(outside) = NaN;
            end

            X(activeIndex) = activeX;
        end

        if realization == 1
            particleTrajectories(:,k+1) = ...
                X(overlayParticleIndices);
        end

        slot = comparisonSlot(k+1);

        if slot > 0

            [empiricalDensity,metrics] = ...
                compare_state( ...
                    X,N, ...
                    meanFieldComparison(:,slot), ...
                    comparisonEdges, ...
                    comparisonDx, ...
                    boundaryCondition);

            empiricalDensitySum(:,slot) = ...
                empiricalDensitySum(:,slot) ...
                +empiricalDensity;

            l1Error(slot,realization) = metrics.l1;
            l2Error(slot,realization) = metrics.l2;
            w1Error(slot,realization) = metrics.w1;
            massError(slot,realization) = metrics.mass;
        end
    end

    finalParticles(:,realization) = X;

    fprintf('Realisation %d/%d complete.\n', ...
        realization,options.numRealizations);
end

empiricalDensityMean = ...
    empiricalDensitySum ...
    ./options.numRealizations;

validation.options = options;
validation.time = comparisonTimes;
validation.comparisonIndices = comparisonIndices;
validation.comparisonEdges = comparisonEdges;
validation.comparisonCentres = comparisonCentres;
validation.comparisonDx = comparisonDx;
validation.meanFieldDensity = meanFieldComparison;
validation.empiricalDensityMean = empiricalDensityMean;
validation.particleTrajectories = particleTrajectories;
validation.overlayParticleIndices = overlayParticleIndices;
validation.finalParticles = finalParticles;

validation.meanErrors.l1 = ...
    mean(l1Error,2);

validation.meanErrors.l2 = ...
    mean(l2Error,2);

validation.meanErrors.w1 = ...
    mean(w1Error,2,'omitnan');

validation.meanErrors.mass = ...
    mean(massError,2);

fprintf('Final mean L1 error: %.3e\n', ...
    validation.meanErrors.l1(end));

fprintf('Final mean W1 error: %.3e\n', ...
    validation.meanErrors.w1(end));

fprintf('Final mass error: %.3e\n', ...
    validation.meanErrors.mass(end));

if options.plot
    plot_validation(validation,cfg,Rho,Y);
end

end

function options = complete_options(options,cfg)

options = set_default( ...
    options,'numParticles',500);

options = set_default( ...
    options,'numRealizations',1);

options = set_default( ...
    options,'comparisonEvery',10);

options = set_default( ...
    options,'initialSampling','quantile');

options = set_default( ...
    options,'maxOverlayParticles',Inf);

options = set_default( ...
    options,'plot',true);

if ~isfield(options,'numComparisonCells') || ...
        isempty(options.numComparisonCells)

    options.numComparisonCells = min( ...
        cfg.numCells, ...
        max(20,min(200, ...
            round(options.numParticles/10))));
end

if ~isfield(options,'interactionBlockSize') || ...
        isempty(options.interactionBlockSize)

    options.interactionBlockSize = min( ...
        500,options.numParticles);
end

if isfield(cfg,'randomSeed')
    defaultSeed = cfg.randomSeed+1000;
else
    defaultSeed = 1042;
end

options = set_default( ...
    options,'randomSeed',defaultSeed);

if isinf(options.maxOverlayParticles)
    options.maxOverlayParticles = ...
        options.numParticles;
end

options.initialSampling = validatestring( ...
    lower(char(options.initialSampling)), ...
    {'quantile','iid','stratified'});

end

function output = ...
    set_default(input,fieldName,defaultValue)

output = input;

if ~isfield(output,fieldName) || ...
        isempty(output.(fieldName))

    output.(fieldName) = defaultValue;
end

end

function X = sample_initial_particles( ...
    rho0,cfg,numParticles,samplingType)

cellMass = ...
    max(rho0(:),0).*cfg.dx;

cellMass = ...
    cellMass./sum(cellMass);

positiveCells = find(cellMass > 0);
positiveMass = cellMass(positiveCells);

cumulativeMass = cumsum(positiveMass);
cumulativeMass(end) = 1;

switch samplingType

    case 'quantile'
        probabilityLevel = ...
            ((1:numParticles).'-0.5) ...
            ./numParticles;

    case 'iid'
        probabilityLevel = ...
            rand(numParticles,1);

    case 'stratified'
        probabilityLevel = ...
            ((0:numParticles-1).' ...
            +rand(numParticles,1)) ...
            ./numParticles;
end

positiveBin = discretize( ...
    probabilityLevel, ...
    [0;cumulativeMass]);

lowerMass = ...
    [0;cumulativeMass(1:end-1)];

fractionWithinCell = ...
    (probabilityLevel ...
    -lowerMass(positiveBin)) ...
    ./positiveMass(positiveBin);

cellIndex = ...
    positiveCells(positiveBin);

X = ...
    cfg.cellEdges(cellIndex) ...
    +cfg.dx.*fractionWithinCell;

end

function velocity = particle_interaction_velocity( ...
    X,cfg,blockSize,normalisation,boundaryCondition)

numActive = numel(X);
blockSize = min(blockSize,numActive);

velocity = zeros(numActive,1);
transposedX = X.';

for firstParticle = 1:blockSize:numActive

    lastParticle = min( ...
        firstParticle+blockSize-1, ...
        numActive);

    particleBlock = ...
        firstParticle:lastParticle;

    displacement = ...
        X(particleBlock)-transposedX;

    if strcmp(boundaryCondition,'periodic')
        displacement = periodic_displacement( ...
            displacement,cfg.domain);
    end

    weight = cfg.followerKernel( ...
        abs(displacement), ...
        cfg.followerKernelParameters);

    velocity(particleBlock) = ...
        -sum(weight.*displacement,2) ...
        ./normalisation;
end

end

function displacement = ...
    periodic_displacement(displacement,domain)

domainWidth = ...
    domain.upper-domain.lower;

displacement = mod( ...
    displacement+0.5.*domainWidth, ...
    domainWidth) ...
    -0.5.*domainWidth;

end

function state = wrap_periodic(state,domain)

domainWidth = ...
    domain.upper-domain.lower;

state = domain.lower+mod( ...
    state-domain.lower,domainWidth);

end

function state = reflect_state(state,domain)

domainWidth = ...
    domain.upper-domain.lower;

shifted = mod( ...
    state-domain.lower, ...
    2.*domainWidth);

state = domain.lower+min( ...
    shifted, ...
    2.*domainWidth-shifted);

end

function coarseDensity = restrict_density( ...
    fineDensity,coarseEdges,cfg)

fineMass = ...
    max(fineDensity(:),0).*cfg.dx;

fineCdf = ...
    [0;cumsum(fineMass)];

coarseCdf = interp1( ...
    cfg.cellEdges, ...
    fineCdf, ...
    coarseEdges, ...
    'linear');

coarseDensity = ...
    max(diff(coarseCdf),0) ...
    ./(coarseEdges(2)-coarseEdges(1));

end

function [empiricalDensity,metrics] = ...
    compare_state( ...
        X,totalParticles,meanFieldDensity, ...
        edges,dx,boundaryCondition)

counts = histcounts( ...
    X(isfinite(X)),edges);

empiricalDensity = ...
    counts(:)./(totalParticles.*dx);

metrics = compare_densities( ...
    empiricalDensity,meanFieldDensity, ...
    dx,boundaryCondition);

end

function metrics = compare_densities( ...
    empiricalDensity,meanFieldDensity, ...
    dx,boundaryCondition)

empiricalDensity = empiricalDensity(:);
meanFieldDensity = meanFieldDensity(:);

difference = ...
    empiricalDensity-meanFieldDensity;

metrics.l1 = ...
    dx.*sum(abs(difference));

metrics.l2 = ...
    sqrt(dx.*sum(difference.^2));

empiricalMass = ...
    max(empiricalDensity,0).*dx;

meanFieldMass = ...
    max(meanFieldDensity,0).*dx;

empiricalTotal = sum(empiricalMass);
meanFieldTotal = sum(meanFieldMass);

metrics.mass = ...
    abs(empiricalTotal-meanFieldTotal);

if empiricalTotal <= 0 || meanFieldTotal <= 0
    metrics.w1 = NaN;
    return;
end

empiricalMass = ...
    empiricalMass./empiricalTotal;

meanFieldMass = ...
    meanFieldMass./meanFieldTotal;

if strcmp(boundaryCondition,'periodic')

    cumulativeDifference = ...
        cumsum(empiricalMass-meanFieldMass);

    shift = median(cumulativeDifference);

    metrics.w1 = ...
        dx.*sum(abs( ...
            cumulativeDifference-shift));
else
    metrics.w1 = piecewise_w1( ...
        empiricalMass,meanFieldMass,dx);
end

end

function distance = piecewise_w1( ...
    massA,massB,dx)

massDifference = ...
    massA(:)-massB(:);

cdfRight = cumsum(massDifference);
cdfLeft = [0;cdfRight(1:end-1)];

leftMagnitude = abs(cdfLeft);
rightMagnitude = abs(cdfRight);

sameSign = ...
    cdfLeft.*cdfRight >= 0;

cellArea = zeros(size(cdfLeft));

cellArea(sameSign) = ...
    0.5.*dx.*( ...
        leftMagnitude(sameSign) ...
        +rightMagnitude(sameSign));

crossesZero = ~sameSign;

if any(crossesZero)

    denominator = ...
        leftMagnitude(crossesZero) ...
        +rightMagnitude(crossesZero);

    cellArea(crossesZero) = ...
        0.5.*dx.*( ...
            leftMagnitude(crossesZero).^2 ...
            +rightMagnitude(crossesZero).^2) ...
        ./denominator;
end

distance = sum(cellArea);

end

function plot_validation(validation,cfg,Rho,Y)

figure('Name','Particles over mean-field density');

imagesc(cfg.time,cfg.cellCentres,Rho);
axis xy tight;
colormap(turbo(256));

finiteDensity = ...
    Rho(isfinite(Rho) & Rho >= 0);

sortedDensity = sort(finiteDensity(:));

colourIndex = max( ...
    1,ceil(0.995*numel(sortedDensity)));

colourMaximum = ...
    sortedDensity(colourIndex);

if colourMaximum <= 0
    colourMaximum = 1;
end

clim([0,colourMaximum]);

hold on;

plot( ...
    cfg.time, ...
    validation.particleTrajectories.', ...
    'w-', ...
    'LineWidth',0.35);

plot(cfg.time,Y,'w-','LineWidth',3);
plot(cfg.time,Y,'k-','LineWidth',1.4);
yline(cfg.target,'w--','LineWidth',1.5);

xlabel('t');
ylabel('x');

colourBar = colorbar;
colourBar.Label.String = '\rho(t,x)';

numComparisons = numel(validation.time);

snapshotSlots = unique(round( ...
    linspace( ...
        1,numComparisons, ...
        min(4,numComparisons))));

figure('Name','Density comparison');

tiledlayout( ...
    2,2, ...
    'TileSpacing','compact', ...
    'Padding','compact');

for index = 1:numel(snapshotSlots)

    slot = snapshotSlots(index);
    nexttile;

    plot( ...
        validation.comparisonCentres, ...
        validation.meanFieldDensity(:,slot), ...
        'LineWidth',1.8);

    hold on;

    plot( ...
        validation.comparisonCentres, ...
        validation.empiricalDensityMean(:,slot), ...
        '--', ...
        'LineWidth',1.5);

    xlabel('x');
    ylabel('\rho');

    title(sprintf( ...
        't = %.3g', ...
        validation.time(slot)));

    grid on;
end

figure('Name','Validation errors');

semilogy( ...
    validation.time, ...
    validation.meanErrors.l1, ...
    'LineWidth',1.5);

hold on;

semilogy( ...
    validation.time, ...
    validation.meanErrors.l2, ...
    'LineWidth',1.5);

semilogy( ...
    validation.time, ...
    validation.meanErrors.w1, ...
    'LineWidth',1.5);

xlabel('t');
ylabel('Error');
legend('L^1','L^2','W_1','Location','best');
grid on;

end